#!/usr/bin/env bash
# One-shot bootstrap for a fresh machine. Idempotent: re-running only fills in what is missing.
#   1. checks prerequisites          5. creates .env from .env.example if missing
#   2. downloads restic + autorestic 6. generates sample data
#   3. installs npm dependencies     7. starts the Docker backends
#   4. generates repository keys     8. initialises the restic repositories + baseline backups
set -euo pipefail
cd "$(dirname "$0")"
LAB=$PWD
RESTIC_VERSION=0.19.1
AUTORESTIC_VERSION=1.8.3

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }
need() { command -v "$1" >/dev/null 2>&1 || { echo "missing: $1 ($2)"; MISSING=1; }; }

say "1/8 prerequisites"
MISSING=0
need docker "https://docs.docker.com/get-docker/"
need node "Node.js 22+ (https://nodejs.org)"
need npm "comes with Node.js"
need jq "https://jqlang.github.io/jq/"
need curl "curl"
need bzip2 "bzip2"
docker compose version >/dev/null 2>&1 || { echo "missing: docker compose plugin"; MISSING=1; }
command -v timeout >/dev/null 2>&1 || command -v gtimeout >/dev/null 2>&1 || echo "note: no 'timeout' command (macOS: brew install coreutils); backups will run without a timeout"
[ "$MISSING" -eq 0 ] || { echo "install the missing tools and re-run"; exit 1; }
NODE_MAJOR=$(node -p 'process.versions.node.split(".")[0]')
[ "$NODE_MAJOR" -ge 22 ] || { echo "Node.js 22+ required (found $(node -v))"; exit 1; }
echo "ok: docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo '?'), node $(node -v), jq $(jq --version)"

say "2/8 restic $RESTIC_VERSION and autorestic $AUTORESTIC_VERSION in bin/"
OS=$(uname -s | tr '[:upper:]' '[:lower:]'); ARCH=$(uname -m)
case "$ARCH" in x86_64|amd64) ARCH=amd64 ;; aarch64|arm64) ARCH=arm64 ;; *) echo "unsupported arch $ARCH"; exit 1 ;; esac
case "$OS" in linux|darwin) ;; *) echo "unsupported OS $OS (use WSL on Windows)"; exit 1 ;; esac
mkdir -p bin
fetch() { # $1=name $2=url
  if [ -x "bin/$1" ] && "bin/$1" --version 2>/dev/null | grep -q "$3"; then echo "ok: bin/$1 already present"; return; fi
  echo "downloading $2"; curl -fsSL -o "bin/$1.bz2" "$2"; bzip2 -df "bin/$1.bz2"; chmod +x "bin/$1"
}
fetch restic "https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/restic_${RESTIC_VERSION}_${OS}_${ARCH}.bz2" "$RESTIC_VERSION"
fetch autorestic "https://github.com/cupcakearmy/autorestic/releases/download/v${AUTORESTIC_VERSION}/autorestic_${AUTORESTIC_VERSION}_${OS}_${ARCH}.bz2" "$AUTORESTIC_VERSION"
export PATH="$LAB/bin:$PATH"
restic version; autorestic --version

say "3/8 npm dependencies"
[ -d node_modules/ai ] && echo "ok: already installed" || npm install --no-fund --no-audit

say "4/8 repository keys (.autorestic.env)"
if [ -f .autorestic.env ]; then echo "ok: .autorestic.env exists, keeping it"; else
  gen() { node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))'; }
  {
    echo "# Generated by setup.sh. Repository keys for restic; losing them means losing the backups."
    for b in LOCAL REMOTE QUOTA; do echo "AUTORESTIC_${b}_RESTIC_PASSWORD=$(gen)"; done
  } > .autorestic.env; chmod 600 .autorestic.env; echo "generated 3 keys"
fi

say "5/8 .env"
if [ -f .env ]; then echo "ok: .env exists"; else cp .env.example .env; chmod 600 .env; echo "created .env from .env.example"; fi
grep -q '^LAB_UID=' .env && sed -i.bak "s/^LAB_UID=.*/LAB_UID=$(id -u)/; s/^LAB_GID=.*/LAB_GID=$(id -g)/" .env || printf 'LAB_UID=%s\nLAB_GID=%s\n' "$(id -u)" "$(id -g)" >> .env
rm -f .env.bak
if ! grep -qE '^AI_GATEWAY_API_KEY=.+' .env; then
  echo "!! AI_GATEWAY_API_KEY is empty in .env: backups will work, but the Jev triage will fail until you set it"
fi

say "6/8 sample data (data/)"
if [ -d data/docs ]; then echo "ok: data/ exists"; else
  mkdir -p data/docs data/media
  for i in $(seq 1 20); do printf 'Document %s\nLorem ipsum dolor sit amet, line %s.\n' "$i" "$i" > "data/docs/doc-$i.txt"; done
  head -c 12000000 /dev/urandom > data/media/video-1.bin
  head -c 3000000 /dev/urandom > data/media/photo-1.bin
  echo "generated 20 text files + 15 MB of binary data"
fi
mkdir -p logs repos/local repos/rest repos/quota

say "7/8 Docker backends"
docker compose up -d
for p in 8500 8501; do
  for i in $(seq 1 30); do curl -s -o /dev/null "http://127.0.0.1:$p/" && break; sleep 1; done
  curl -s -o /dev/null "http://127.0.0.1:$p/" && echo "ok: rest-server on $p" || { echo "rest-server on $p not answering"; exit 1; }
done

say "8/8 restic repositories"
autorestic check --ci 2>&1 | grep -vE '^Using (config|lock)' || true
if ! autorestic exec -b local --ci -- snapshots --compact 2>/dev/null | grep -q 'ar:location:docs-local'; then
  autorestic backup -l docs-local --ci > logs/baseline-docs-local.log 2>&1 && echo "baseline snapshot: docs-local"
  autorestic backup -l docs-remote --ci > logs/baseline-docs-remote.log 2>&1 && echo "baseline snapshot: docs-remote"
else echo "ok: baseline snapshots exist"; fi

say "done"
cat <<TXT
Next:
  ./backup.sh docs-local     one backup with triage if it fails
  ./run-all.sh               the 7 failure scenarios
  npm run demo               the UI at http://127.0.0.1:${DEMO_PORT:-8600}
  docker compose down        stop the backends
TXT
